update

diff --git a/.github/workflows/logica-release.yml b/.github/workflows/logica-release.yml
--- a/.github/workflows/logica-release.yml
+++ b/.github/workflows/logica-release.yml
@@ -18,14 +18,34 @@ jobs:
           ref: main
           clean: true
 
-      - name: Fail if branch exists
+#      - name: Fail if branch exists
+#        run: |
+#          if git show-ref ${{ github.event.inputs.branch-name }}; then
+#            echo "${{ github.event.inputs.branch-name }} exists. Exiting with code 1."
+#            exit 1
+#          else
+#            echo "${{ github.event.inputs.branch-name }} does not exist. Continuing."
+#          fi
+
+      - name: Check if branch exists
+        id: check-branch
         run: |
-          if git show-ref ${{ github.event.inputs.branch-name }}; then
-            echo "${{ github.event.inputs.branch-name }} exists. Exiting with code 1."
-            exit 1
-          else
-            echo "${{ github.event.inputs.branch-name }} does not exist. Continuing."
-          fi
+            branch_name="${{ github.event.inputs.branch-name }}"
+            if git rev-parse --verify "$branch_name" >/dev/null 2>&1; then
+            echo "Branch '$branch_name' already exists."
+            echo "::set-output name=branch-exists::true"
+            else
+            echo "Branch '$branch_name' does not exist."
+            echo "::set-output name=branch-exists::false"
+            fi
+
+            - name: Stop if branch exists
+              run: |
+                branch_exists="${{ steps.check-branch.outputs.branch-exists }}"
+                if [[ "$branch_exists" == "true" ]]; then
+                  echo "Action stopped because branch already exists."
+                  exit 1
+                fi
 
       - name: Create and switch to new branch
         run: |
